e_data <- read.table("household_power_consumption.txt",header=T,sep=";",colClasses=c("character"))
sub_data <- subset(e_data,as.Date(e_data$Date,"%d/%m/%Y") == "2007-02-01" | as.Date(e_data$Date,"%d/%m/%Y") == "2007-02-02")
remove(e_data)
d <- paste(sub_data$Date,sub_data$Time)
update_time <- strptime(d,format="%d/%m/%Y %H:%M:%S")
plot(update_time,sub_data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
points(update_time,sub_data$Sub_metering_2,col="red",lwd=1,type="l")
points(update_time,sub_data$Sub_metering_3,col="blue",lwd=1,type="l")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lwd=1)
dev.copy(png,file="plot3.png",width=480,height=480)
dev.off()